### PR TITLE
Prepare for enabling Travis CI.

### PR DESCRIPTION
**Pull request by 130s**
This travis hook config does not do much yet; it only tries to confirm if the project builds. Once test cases are added we can run them from travis too (as suggested https://github.com/arebgun/dynamixel_motor/issues/31 by @kamiccolo).

@arebgun Could you setup travis hook for this repository? http://docs.travis-ci.com/user/getting-started/

### CODE REVIEW

**Comment by 130s** [comment]
Ping @arebgun

**Comment by 130s** [comment]
@arebgun Could you enable `travis` for this repo? I think you can simply access https://travis-ci.org/profile/arebgun and slide the bar on dynamixel_motor to do that and that's it.

**Comment by arebgun** [comment]
@130s done.

**Comment by 130s** [comment]
Looks like it. Thanks!

**Comment by k-okada** [comment]
typo travis.yaml should be travis.yml

**Pull request merged**
